server {
    listen *:9000;
    listen *:9001;
    listen *:9002;
    listen *:9003;

    location / {
        default_type text/plain;
        return 200 "Hello $remote_addr:$remote_port!\nThis is $server_addr:$server_port speaking.\n";
    }
}
